name: Build & Test PR

on:
  pull_request:
    branches: [ main ]

env:
    NETCORE_VERSION: '7.0.x'
    PROJECT_NAME: TextEditor

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setting up .NET Core SDK ${{ env.NETCORE_VERSION }}...
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restoring packages...
      run: dotnet restore

    - name: Build Local Storage
      run: dotnet build -c Release --no-restore src/Blazored.$PROJECT_NAME/Blazored.$PROJECT_NAME.csproj